stages:
    - Centos Deployment

centos:
    image: centos:latest
    stage: Centos Deployment
    script:
        - dnf install -y curl git zsh
        - sudo su "${USER}"
        - curl "https://gitlab.orion-technologies.io/philler/dot-files/-/raw/Development/install.bash" | bash