stages:
    - Centos Deployment

centos:
    image: centos:latest
    stage: Centos Deployment
    script:
        - dnf update -y
        - dnf install -y curl git zsh && curl "https://gitlab.orion-technologies.io/philler/dot-files/-/raw/Development/install.bash" | bash